export type GameLocale = "zh-CN" | "en";

const copy = {
  "zh-CN": {
    online: "仅 1 人在线",
    connecting: "正在接入后台频道……",
    retry: "重新连接",
    backendGroup: "留存协议｜后台群聊",
    system: "系统公告",
    chooseReply: "选择一条回复",
    chapter: "当前频道",
    runLength: "预计 10–15 分钟",
    start: "接入第七码头",
    noise: "噪声等级",
    noiseHint: "通关后开放更复杂的规则，不只增加生命。",
    available: "已开放",
    encrypted: "频道未解密",
    roster: "后台成员",
    map: "频道拓扑",
    mapHint: "选择一个发光节点；未走的路径会在本局关闭。",
    hp: "同步率",
    deck: "牌组",
    relics: "插件",
    abandon: "放弃本局",
    abandonConfirm: "放弃后地图和本局牌组会重置，确定吗？",
    combat: "信号冲突",
    turn: "回合",
    bandwidth: "带宽",
    beacon: "航标",
    distortion: "失真",
    intent: "下一意图",
    draw: "抽牌",
    discard: "弃牌",
    exhaust: "移除",
    endTurn: "结束回合",
    selectTarget: "先选择一个目标",
    reward: "截获一段新信号",
    rewardHint: "加入牌组，或跳过以保持精简。",
    skip: "跳过",
    event: "频道异常",
    rest: "临时休整点",
    heal: "恢复 14 点同步率",
    remove: "删除一张牌",
    removeHint: "选择要从本局牌组永久移除的牌。",
    back: "返回",
    victory: "频道恢复为非标准状态",
    defeat: "连接已经中断",
    abandoned: "本局已主动断开",
    continue: "返回后台群聊",
    unavailable: "当前操作不可用",
    authError: "Telegram 身份验证失败，请从机器人重新打开游戏。",
    networkError: "连接失败；服务器状态没有丢失。",
    nodeCombat: "冲突",
    nodeElite: "强信号",
    nodeEvent: "异常",
    nodeStory: "主线",
    nodeRest: "休整",
    nodeBoss: "最优人格",
    locked: "未开放",
    activeRun: "检测到未完成频道，正在恢复……",
    lowBandwidth: "带宽不足",
    unplayable: "乱码牌无法主动打出",
    routeReady: "攻击＋防御＋信号：航线完成",
    noRelics: "暂无插件"
  },
  en: {
    online: "Only 1 online",
    connecting: "Connecting to the backstage channel…",
    retry: "Reconnect",
    backendGroup: "RETENTION PROTOCOL | Backstage",
    system: "System notice",
    chooseReply: "Choose a reply",
    chapter: "Current channel",
    runLength: "About 10–15 minutes",
    start: "Enter the Seventh Dock",
    noise: "Noise level",
    noiseHint: "Clears unlock rule changes—not just larger health bars.",
    available: "Available",
    encrypted: "Channel encrypted",
    roster: "Backstage members",
    map: "Channel topology",
    mapHint: "Choose a glowing node. Unused routes close for this run.",
    hp: "Sync",
    deck: "Deck",
    relics: "Plugins",
    abandon: "Abandon run",
    abandonConfirm: "The map and run deck will reset. Abandon this run?",
    combat: "Signal conflict",
    turn: "Turn",
    bandwidth: "Bandwidth",
    beacon: "Beacon",
    distortion: "Distortion",
    intent: "Next intent",
    draw: "Draw",
    discard: "Discard",
    exhaust: "Exhaust",
    endTurn: "End turn",
    selectTarget: "Select a target first",
    reward: "Intercepted signal",
    rewardHint: "Add it to your deck, or skip to stay lean.",
    skip: "Skip",
    event: "Channel anomaly",
    rest: "Temporary rest point",
    heal: "Restore 14 Sync",
    remove: "Delete a card",
    removeHint: "Choose a card to remove from this run permanently.",
    back: "Back",
    victory: "Channel restored to a nonstandard state",
    defeat: "Connection lost",
    abandoned: "Run disconnected",
    continue: "Return to backstage",
    unavailable: "That operation is unavailable",
    authError: "Telegram authentication failed. Reopen the game from the bot.",
    networkError: "Connection failed; authoritative state was not lost.",
    nodeCombat: "Conflict",
    nodeElite: "Strong signal",
    nodeEvent: "Anomaly",
    nodeStory: "Story",
    nodeRest: "Rest",
    nodeBoss: "Optimal persona",
    locked: "Locked",
    activeRun: "Unfinished channel found. Restoring…",
    lowBandwidth: "Not enough bandwidth",
    unplayable: "Corrupted cards cannot be played directly",
    routeReady: "Attack + Defense + Signal: route complete",
    noRelics: "No plugins yet"
  }
} as const;

export type GameCopyKey = keyof (typeof copy)["zh-CN"];

export const gameText = (locale: GameLocale, key: GameCopyKey): string => copy[locale][key];
