export type GameLocale = "zh-CN" | "en";

const copy = {
  "zh-CN": {
    online: "仅 1 人在线",
    connecting: "正在接入异常频道……",
    retry: "重新连接",
    backendGroup: "留存协议｜后台群聊",
    system: "系统公告",
    chooseReply: "选择一条回复",
    chapter: "当前频道",
    runLength: "预计 6–8 分钟",
    start: "再次潜入第七码头",
    noise: "噪声等级",
    noiseHint: "通关后开放新的弹幕、路线和失真规则。",
    roster: "后台成员",
    map: "频道拓扑",
    mapHint: "选择发光节点；未走的路径将在本局关闭。",
    hp: "同步率",
    modules: "模块",
    plugins: "频道插件",
    abandon: "放弃本局",
    abandonConfirm: "放弃后本局路线和模块会重置，确定吗？",
    reward: "截获频道模块",
    rewardHint: "选择一个立即安装，最多六种、每种三级。",
    pluginFound: "精英插件",
    skip: "跳过",
    event: "频道异常",
    rest: "临时休整点",
    repair: "修复 30% 同步率",
    tune: "调谐一个模块",
    tuneHint: "选择一个未达到三级的模块。",
    back: "返回",
    victory: "最优人格已离线",
    defeat: "连接已经中断",
    abandoned: "本局已主动断开",
    continue: "返回后台群聊",
    noiseUnlocked: "噪声挑战已开放。记忆碎片已记录。",
    unavailable: "当前操作不可用；房间将从相同种子重新开始。",
    authError: "Telegram 身份验证失败，请从机器人重新打开游戏。",
    networkError: "连接失败；权威 Run 没有丢失。",
    nodeTutorial: "握手",
    nodeCombat: "冲突",
    nodeElite: "强信号",
    nodeEvent: "异常",
    nodeStory: "主线",
    nodeRest: "休整",
    nodeBoss: "最优人格",
    noPlugins: "暂无插件",
  },
  en: {
    online: "Only 1 online",
    connecting: "Connecting to an anomalous channel…",
    retry: "Reconnect",
    backendGroup: "RETENTION PROTOCOL | Backstage",
    system: "System notice",
    chooseReply: "Choose a reply",
    chapter: "Current channel",
    runLength: "About 6–8 minutes",
    start: "Dive into the Seventh Dock",
    noise: "Noise level",
    noiseHint: "Clears unlock new bullet, route, and distortion rules.",
    roster: "Backstage members",
    map: "Channel topology",
    mapHint: "Choose a glowing node. Unused routes close for this run.",
    hp: "Sync",
    modules: "Modules",
    plugins: "Channel plugins",
    abandon: "Abandon run",
    abandonConfirm: "This run's route and modules will reset. Abandon it?",
    reward: "Intercepted channel module",
    rewardHint:
      "Install one now. Carry up to six types, each up to level three.",
    pluginFound: "Elite plugin",
    skip: "Skip",
    event: "Channel anomaly",
    rest: "Temporary rest point",
    repair: "Restore 30% Sync",
    tune: "Tune one module",
    tuneHint: "Choose a module below level three.",
    back: "Back",
    victory: "Optimal persona offline",
    defeat: "Connection lost",
    abandoned: "Run disconnected",
    continue: "Return to backstage",
    noiseUnlocked: "Noise challenge unlocked. Memory fragment recorded.",
    unavailable:
      "That action was rejected. The room will restart from the same seed.",
    authError: "Telegram authentication failed. Reopen the game from the bot.",
    networkError: "Connection failed; the authoritative run is safe.",
    nodeTutorial: "Handshake",
    nodeCombat: "Conflict",
    nodeElite: "Strong signal",
    nodeEvent: "Anomaly",
    nodeStory: "Story",
    nodeRest: "Rest",
    nodeBoss: "Optimal persona",
    noPlugins: "No plugins yet",
  },
} as const;

export type GameCopyKey = keyof (typeof copy)["zh-CN"];
export const gameText = (locale: GameLocale, key: GameCopyKey): string =>
  copy[locale][key];
