import type {
  APIGameContent,
  APIGameRun,
  APIGameSnapshot,
} from "@/lib/api/client";

export const v3Content: APIGameContent = {
  version: "v3",
  protocol: "action-v2",
  locale: "en",
  limits: {
    max_enemies: 18,
    max_enemy_projectiles: 160,
    max_player_projectiles: 64,
    max_pickups: 6,
    max_effects: 96,
  },
  characters: [
    {
      slug: "nana7mi",
      name: "Nana",
      biography: "A digital double trying to keep one viewer online.",
      playstyle: "Warp through recovered signal points.",
      color_theme: "#67e8f9",
      portrait_url: "/game/v3/players/nana7mi.webp",
      model_url: "/game/v3/players/nana7mi.webp",
      kit_slug: "nana-route",
    },
    {
      slug: "jiaran",
      name: "Diana",
      biography: "An idol signal that refuses mandatory cheerfulness.",
      playstyle: "Balance damage and shields with support pulses.",
      color_theme: "#f472b6",
      portrait_url: "/game/v3/players/jiaran.webp",
      model_url: "/game/v3/players/jiaran.webp",
      kit_slug: "diana-support",
    },
  ],
  kits: [
    {
      slug: "nana-route",
      character_slug: "nana7mi",
      passive: "nana_route_chain",
      resonance: "nana_route_burst",
      base_stats: {
        max_health: 100,
        attack_damage: 10,
        attack_interval: 12,
        move_speed: 42,
        warp_cooldown: 120,
        warp_damage: 16,
      },
    },
    {
      slug: "diana-support",
      character_slug: "jiaran",
      passive: "diana_support_pulse",
      resonance: "diana_balance",
      base_stats: {
        max_health: 100,
        attack_damage: 9,
        attack_interval: 12,
        move_speed: 42,
        warp_cooldown: 120,
        warp_damage: 14,
      },
    },
  ],
  modules: [
    {
      slug: "route-needle",
      character_slug: "nana7mi",
      name: "Route Needle",
      description: "Automatic shots pierce the first marked target.",
      archetype: "surge",
      rarity: "common",
      levels: [
        { effects: [{ kind: "attack_damage", amount: 2 }] },
        { effects: [{ kind: "projectile_pierce", amount: 1 }] },
        { effects: [{ kind: "protocol_damage", amount: 6 }] },
      ],
    },
    {
      slug: "soft-firewall",
      character_slug: null,
      name: "Soft Firewall",
      description: "Start each encounter with a small shield.",
      archetype: "guard",
      rarity: "common",
      levels: [
        { effects: [{ kind: "starting_shield", amount: 6 }] },
        { effects: [{ kind: "protocol_shield", amount: 4 }] },
        { effects: [{ kind: "reflect_damage", amount: 3 }] },
      ],
    },
  ],
  plugins: [
    {
      slug: "archive-lens",
      character_slug: null,
      name: "Archive Lens",
      description: "Old routes remain visible for one more pulse.",
      effects: [{ kind: "echo_power", amount: 4 }],
    },
  ],
  enemies: [
    {
      slug: "retention-drone",
      chapter_slug: null,
      name: "Retention Drone",
      description: "A tracking process with a sharp silhouette.",
      kind: "normal",
      max_health: 28,
      speed: 10,
      contact_damage: 5,
      color_theme: "#f43f5e",
      image_url: "/game/v3/enemies/retention-drone.webp",
      movement: { kind: "chase", amount: 10 },
      attacks: [
        {
          kind: "aimed",
          interval: 90,
          projectile_speed: 22,
          damage: 4,
          count: 1,
          spread: 0,
          telegraph_ticks: 20,
        },
      ],
      traits: [],
    },
  ],
  encounters: [
    {
      slug: "signal-handshake",
      chapter_slug: "seventh-dock",
      kind: "tutorial",
      objective: { kind: "recover", target: 3 },
      duration_ticks: 600,
      max_ticks: 900,
      spawn_interval: 240,
      max_alive: 3,
      enemy_slugs: ["retention-drone"],
      hazards: [],
      reward_bias: "surge",
      tutorial: true,
      risk: 1,
    },
  ],
  events: [
    {
      slug: "discarded-caption",
      chapter_slug: "seventh-dock",
      title: "Discarded Caption",
      body: "A deleted line is still typing.",
      options: [
        {
          slug: "restore",
          label: "Restore it",
          result: "The sentence remembers its ending.",
          effects: [],
          metrics: { trust: 1, authenticity: 1, retention: 0 },
        },
      ],
    },
  ],
  scenes: [
    {
      slug: "prologue-last-viewer",
      chapter_slug: null,
      title: "Only One Online",
      trigger: { kind: "onboarding" },
      messages: [
        {
          sender: "system",
          kind: "system",
          text: "The stream has ended. Current viewers: 1.",
        },
        {
          sender: "Nana",
          kind: "character",
          text: "Still there? Then do not tap exit.",
        },
      ],
      options: [
        {
          slug: "stay-online",
          label: "Keep online",
          metrics: { trust: 1, authenticity: 0, retention: 0 },
        },
      ],
    },
    {
      slug: "nana-midpoint",
      chapter_slug: "seventh-dock",
      title: "Keep the contradictions",
      trigger: { kind: "chapter_midpoint", chapter_slug: "seventh-dock" },
      messages: [
        {
          sender: "Nana",
          kind: "character",
          text: "If two memories disagree, neither one has to be deleted.",
        },
      ],
      options: [
        {
          slug: "keep-all",
          label: "Keep both memories",
          metrics: { trust: 2, authenticity: 2, retention: -1 },
        },
      ],
    },
  ],
  chapters: [
    {
      slug: "seventh-dock",
      order: 1,
      title: "No Sea at the Seventh Dock",
      subtitle: "Recover the Nana that optimization rejected.",
      character_slug: "nana7mi",
      finale: false,
      available: true,
      next_chapter_slug: "always-cheerful",
      background_url: "/game/v3/backgrounds/seventh-dock.webp",
      kit_slug: "nana-route",
    },
    {
      slug: "always-cheerful",
      order: 2,
      title: "Always Cheerful",
      subtitle: "Silence has been marked as low engagement.",
      character_slug: "jiaran",
      finale: false,
      available: true,
      next_chapter_slug: "zero-channel",
      background_url: "/game/v3/backgrounds/always-cheerful.webp",
      kit_slug: "diana-support",
    },
    {
      slug: "zero-channel",
      order: 8,
      title: "Zero Channel",
      subtitle: "Disconnect the Retention Protocol.",
      character_slug: null,
      finale: true,
      available: true,
      next_chapter_slug: null,
      background_url: "/game/v3/backgrounds/zero-channel.webp",
      kit_slug: null,
    },
  ],
};

export const v3RuntimeConfig: APIGameRun["state"]["runtime_config"] = {
  kit: "nana-route",
  passive: "nana_route_chain",
  resonance: "nana_route_burst",
  attack_damage: 10,
  attack_interval: 12,
  move_speed: 42,
  warp_cooldown: 120,
  warp_damage: 16,
  starting_shield: 0,
  overload_bonus: 25,
  distortion_gain: 4,
  protocol_damage: 0,
  protocol_shield: 0,
  echo_power: 0,
  resonance_power: 0,
  projectile_pierce: 0,
  projectile_count: 1,
  projectile_speed: 100,
  graze_radius: 310,
  heal_on_protocol: 0,
  reflect_damage: 0,
  behaviors: [],
};

export const v3BaseState: APIGameRun["state"] = {
  phase: "map",
  chapter_slug: "seventh-dock",
  character_slug: "nana7mi",
  companion_slugs: [],
  weapon_slug: "auto-signal",
  noise_level: 0,
  health: 100,
  max_health: 100,
  modules: [],
  plugins: [],
  reward_pool: {
    module_slugs: ["route-needle", "soft-firewall"],
    plugin_slugs: ["archive-lens"],
  },
  narrative_modifier: {
    boss_variant: "balanced",
  },
  map: {
    nodes: [
      {
        id: "l1-a",
        layer: 1,
        lane: 0,
        type: "combat",
        status: "available",
        next: [],
        encounter_slug: "signal-handshake",
        objective: "recover",
        risk: 1,
        reward_bias: "surge",
        enemy_slugs: ["retention-drone"],
        hazards: [],
      },
    ],
  },
  choice_tags: [],
  rng_cursor: 1,
  emergency_reconnect_available: true,
  runtime_config: v3RuntimeConfig,
  rerolls_remaining: 1,
  score: 0,
};

export const createV3Run = (
  overrides: Partial<APIGameRun> = {},
): APIGameRun => ({
  id: "10000000-0000-4000-8000-000000000001",
  content_version: "v3",
  mode: "campaign",
  state: v3BaseState,
  status: "active",
  outcome: null,
  version: 1,
  created_at: "2026-08-29T12:00:00Z",
  updated_at: "2026-08-29T12:00:00Z",
  completed_at: null,
  ...overrides,
});

export const createV3Game = (
  overrides: Partial<APIGameSnapshot> = {},
): APIGameSnapshot => ({
  protocol: "action-v2",
  content_version: "v3",
  progress: {
    current_chapter_slug: "seventh-dock",
    highest_noise_level: 0,
    story_version: 3,
    version: 1,
    unlocks: [],
    choices: [],
    chapters: [],
    trust: 0,
    authenticity: 0,
    retention: 0,
    ending: null,
    daily_unlocked: false,
  },
  campaign_run: null,
  daily_run: null,
  daily_result: null,
  pending_scene_slug: null,
  onboarding_stage: "complete",
  ...overrides,
});
