import type {
  ShooterContent,
  ShooterGameRun,
  ShooterGameSnapshot,
  ShooterRunState,
  ShooterRuntimeConfig,
} from "@/lib/api/types";

export const v4Runtime: ShooterRuntimeConfig = {
  seed: "frontend-vector-seed",
  duration_ticks: 90,
  player_health: 3,
  starting_rescue_charge: 0,
  encore_level: 0,
  daily: false,
  special_charge_penalty_percent: 0,
  kit: {
    id: "nana7mi",
    max_health: 3,
    attack_damage: 6,
    fire_interval: 6,
    rescue_damage: 30,
    starting_shield: 0,
    move_limit: 1_705,
    special_behavior: "barrage_break",
    special_duration: 30,
  },
  companions: [],
  show_effects: [],
  enemies: [
    {
      id: "spam-bot",
      chassis: "spam-bot",
      health: 12,
      speed: 18,
      contact_damage: 1,
      move_pattern: "drift",
      shot_pattern: "aimed",
      fire_interval: 45,
      projectile_speed: 38,
      damage: 1,
      score: 100,
      telegraph_ticks: 12,
      traits: [],
    },
  ],
  wave: {
    id: "test-wave",
    spawns: [
      {
        at_tick: 0,
        enemy_id: "spam-bot",
        count: 1,
        formation: "center",
        interval_ticks: 0,
      },
    ],
  },
  limits: {
    enemies: 14,
    enemy_projectiles: 120,
    player_projectiles: 48,
    pickups: 12,
    effects: 24,
  },
};

export const v4Content: ShooterContent = {
  version: "v4",
  protocol: "shooter-v1",
  locale: "en",
  rules: {
    tick_rate: 30,
    logical_width: 3_600,
    logical_height: 6_400,
    player_y: 5_200,
    input_columns: 128,
    starting_hearts: 3,
    max_enemies: 14,
    max_enemy_projectiles: 120,
    max_player_projectiles: 48,
    max_pickups: 12,
    max_effects: 24,
    special_charge_max: 100,
    graze_charge: 4,
    waves_per_chapter: 3,
    boss_stages: 3,
  },
  show_effects: [
    {
      id: "double-take",
      name: "Twin Live Feed",
      description: "Fire a second live round.",
      archetype: "power",
      behavior: "twin_shot",
      amount: 1,
    },
    {
      id: "safety-chat",
      name: "Guard Call",
      description: "Rescue also raises a guard.",
      archetype: "guard",
      behavior: "guard_on_special",
      amount: 6,
    },
  ],
  characters: [
    {
      id: "nana7mi",
      name: "Nana",
      biography: "The last signal from the Seventh Dock.",
      playstyle: "Straight shots and decisive rescues.",
      color_theme: "cyan",
      portrait_url: "/game/v4/players/nana7mi.webp",
      sprite_url: "/game/v4/players/nana7mi.webp",
      base_stats: {
        max_health: 3,
        shot_damage: 6,
        shot_interval: 6,
        move_limit: 1_705,
      },
      special: {
        id: "nana-route-break",
        name: "Route Break",
        description: "Clear the barrage and mark the route.",
        charge_cost: 100,
        behavior: "barrage_break",
        power: 30,
        duration_ticks: 30,
      },
    },
  ],
  companions: [
    {
      id: "jiaran-assist",
      character_id: "jiaran",
      name: "Diana Assist",
      description: "Sends a cheering side shot.",
      portrait_url: "/game/v4/players/jiaran.webp",
      assist: {
        trigger: "graze_streak",
        behavior: "side_shot",
        amount: 3,
        cooldown_ticks: 90,
      },
    },
  ],
  enemies: [
    {
      id: "spam-bot",
      name: "Spam Bot",
      description: "Floods the live chat.",
      sprite_url: "/game/v4/enemies/spam-bot.webp",
      max_health: 12,
      speed: 18,
      contact_damage: 1,
      move_pattern: "drift",
      shot_pattern: "aimed",
      shot_interval: 45,
      projectile_speed: 38,
      projectile_damage: 1,
      telegraph_ticks: 12,
      traits: [],
    },
  ],
  chapters: [
    {
      id: "seventh-dock",
      order: 1,
      title: "No Sea at the Seventh Dock",
      subtitle: "Keep one impossible channel on air.",
      featured_character: "nana7mi",
      unlock_companion: "nana7mi-assist",
      background_url: "/game/v4/backgrounds/seventh-dock.webp",
      segments: [
        {
          id: "seventh-dock-1",
          duration_ticks: 90,
          wave_id: "test-wave",
          background_url: "/game/v4/backgrounds/seventh-dock.webp",
          reward_stage: "weapon",
        },
      ],
      waves: [v4Runtime.wave],
      boss: {
        id: "optimal-nana",
        name: "Optimal Nana",
        description: "A version polished until nothing human remains.",
        sprite_url: "/game/v4/bosses/optimal-nana.webp",
        max_health: 90,
        duration_ticks: 90,
        stages: [
          {
            id: "opening",
            health_threshold: 100,
            move_pattern: "anchor",
            shot_pattern: "aimed",
            shot_interval: 30,
            projectile_speed: 35,
            projectile_damage: 1,
            telegraph_ticks: 10,
            special: "route-lock",
          },
          {
            id: "middle",
            health_threshold: 66,
            move_pattern: "sweep",
            shot_pattern: "fan",
            shot_interval: 26,
            projectile_speed: 38,
            projectile_damage: 1,
            telegraph_ticks: 10,
            special: "route-lock",
          },
          {
            id: "final",
            health_threshold: 33,
            move_pattern: "mirror",
            shot_pattern: "ring",
            shot_interval: 22,
            projectile_speed: 40,
            projectile_damage: 1,
            telegraph_ticks: 9,
            special: "route-lock",
          },
        ],
      },
      story: {
        prelude: [
          {
            sender_id: "nana7mi",
            sender: "Nana",
            text: "Still there? Keep the channel open.",
          },
        ],
        intermission: {
          after_segment: 2,
          prompt: "Which signal stays live?",
          messages: [
            { sender_id: "nana7mi", sender: "Nana", text: "Choose quickly." },
            {
              sender_id: "system",
              sender: "Archive",
              text: "Only one vote is retained.",
            },
          ],
          choices: [
            {
              id: "keep-voice",
              label: "Keep her voice",
              result: "The archive leaves the voice untouched.",
              tag: "authenticity",
            },
          ],
        },
        epilogue: [
          { sender_id: "nana7mi", sender: "Nana", text: "We are still here." },
        ],
        replay_recap: [
          { sender_id: "nana7mi", sender: "Nana", text: "One more broadcast." },
        ],
      },
      encore: [
        {
          id: "encore-1",
          name: "Encore I",
          description: "The chat moves faster.",
          enemy_speed_percent: 105,
          projectile_speed_percent: 105,
          special_charge_penalty_percent: 0,
        },
      ],
      endings: [],
    },
  ],
  daily: {
    id: "daily-signal",
    title: "Daily Signal",
    subtitle: "One shared broadcast.",
    seed_timezone: "UTC",
    segment_duration_ticks: 90,
    segment_count: 2,
    show_choice_count: 1,
    rotation_characters: ["nana7mi"],
    wave_ids: ["test-wave"],
    boss_ids: ["optimal-nana"],
    encore_modifier_ids: ["encore-1"],
  },
};

export const v4BaseState: ShooterRunState = {
  phase: "segment",
  chapter_slug: "seventh-dock",
  character_slug: "nana7mi",
  companion_slugs: [],
  encore_level: 0,
  segment_index: 0,
  hearts: 3,
  max_hearts: 3,
  score: 0,
  segment: {
    segment_slug: "seventh-dock-1",
    segment_index: 0,
    seed: "frontend-vector-seed",
    duration_ticks: 90,
    wave_id: "test-wave",
    reward_stage: "weapon",
    background_url: "/game/v4/backgrounds/seventh-dock.webp",
    runtime_config: v4Runtime,
  },
  pending_show_options: [],
  show_effects: [],
  selected_choice_ids: [],
};

export const createV4Run = (
  override: Partial<ShooterGameRun> & { state?: ShooterRunState } = {},
): ShooterGameRun => ({
  id: "10000000-0000-4000-8000-000000000001",
  content_version: "v4",
  mode: "campaign",
  state: v4BaseState,
  status: "active",
  outcome: null,
  version: 1,
  created_at: "2026-08-31T00:00:00Z",
  updated_at: "2026-08-31T00:00:00Z",
  completed_at: null,
  ...override,
});

export const createV4Game = (
  override: Partial<ShooterGameSnapshot> = {},
): ShooterGameSnapshot => ({
  protocol: "shooter-v1",
  content_version: "v4",
  progress: {
    current_chapter_slug: "seventh-dock",
    story_version: 4,
    version: 1,
    chapters: [
      {
        chapter_slug: "seventh-dock",
        highest_encore_level: 0,
        clears: 0,
        best_score: 0,
        updated_at: "2026-08-31T00:00:00Z",
      },
    ],
    unlocks: [
      {
        type: "character",
        content_slug: "nana7mi",
        created_at: "2026-08-31T00:00:00Z",
      },
    ],
    choices: [],
    ending: null,
    daily_unlocked: false,
  },
  campaign_run: null,
  daily_run: null,
  daily_result: null,
  ...override,
});
