/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/content/{version}": {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path: {
                version: "v4";
            };
            cookie?: never;
        };
        get: operations["getGameContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGameState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRunCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/story/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["appendStoryChoiceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/daily/results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicDailyResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
            version: string;
        };
        Readiness: {
            status: string;
            checks: {
                [key: string]: string;
            };
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                request_id: string;
            };
        };
        Slug: string;
        AssetPath: string;
        Rules: {
            /** @constant */
            tick_rate: 30;
            /** @constant */
            logical_width: 3600;
            /** @constant */
            logical_height: 6400;
            /** @constant */
            player_y: 5200;
            /** @constant */
            input_columns: 128;
            /** @constant */
            starting_hearts: 3;
            /** @constant */
            max_enemies: 14;
            /** @constant */
            max_enemy_projectiles: 120;
            /** @constant */
            max_player_projectiles: 48;
            /** @constant */
            max_pickups: 12;
            /** @constant */
            max_effects: 24;
            /** @constant */
            special_charge_max: 100;
            graze_charge: number;
            /** @constant */
            waves_per_chapter: 3;
            /** @constant */
            boss_stages: 3;
        };
        PlayerStats: {
            /** @constant */
            max_health: 3;
            shot_damage: number;
            shot_interval: number;
            move_limit: number;
        };
        LocalizedSpecial: {
            id: components["schemas"]["Slug"];
            name: string;
            description: string;
            /** @constant */
            charge_cost: 100;
            /** @enum {string} */
            behavior: "barrage_break" | "cheer_guard" | "afterimage_replay" | "captain_parry" | "subtitle_flip" | "prism_shift" | "memory_bloom";
            power: number;
            duration_ticks: number;
        };
        LocalizedShowEffect: {
            id: components["schemas"]["Slug"];
            name: string;
            description: string;
            /** @enum {string} */
            archetype: "power" | "guard" | "style";
            /** @enum {string} */
            behavior: "twin_shot" | "piercing_shot" | "spread_shot" | "graze_charge" | "guard_on_special" | "pickup_magnet" | "echo_volley" | "boss_break" | "low_health_power" | "combo_extend" | "companion_charge" | "recovery_drop";
            amount: number;
        };
        LocalizedCharacter: {
            id: components["schemas"]["Slug"];
            name: string;
            biography: string;
            playstyle: string;
            color_theme: string;
            portrait_url: components["schemas"]["AssetPath"];
            sprite_url: components["schemas"]["AssetPath"];
            base_stats: components["schemas"]["PlayerStats"];
            special: components["schemas"]["LocalizedSpecial"];
        };
        Assist: {
            /** @enum {string} */
            trigger: "segment_start" | "graze_streak" | "low_health" | "special_used" | "boss_stage" | "pickup_chain" | "wave_clear";
            /** @enum {string} */
            behavior: "side_shot" | "shield" | "echo_shot" | "clear_lane" | "convert_bullet" | "focus_beam" | "heal";
            amount: number;
            cooldown_ticks: number;
        };
        LocalizedCompanion: {
            id: components["schemas"]["Slug"];
            character_id: components["schemas"]["Slug"];
            name: string;
            description: string;
            portrait_url: components["schemas"]["AssetPath"];
            assist: components["schemas"]["Assist"];
        };
        LocalizedEnemy: {
            /** @enum {string} */
            id: "spam-bot" | "clip-cutter" | "caption-blob" | "black-screen-ghost" | "gift-thief" | "censor-frame";
            name: string;
            description: string;
            sprite_url: components["schemas"]["AssetPath"];
            max_health: number;
            speed: number;
            contact_damage: number;
            /** @enum {string} */
            move_pattern: "drift" | "sweep" | "dive" | "orbit" | "anchor" | "mirror";
            /** @enum {string} */
            shot_pattern: "aimed" | "fan" | "lane" | "ring" | "delayed" | "beam";
            shot_interval: number;
            projectile_speed: number;
            projectile_damage: number;
            telegraph_ticks: number;
            traits: ("shield_link" | "split" | "steal_pickup" | "armor" | "echo" | "jammer")[];
        };
        ContentSegment: {
            id: components["schemas"]["Slug"];
            duration_ticks: number;
            wave_id: components["schemas"]["Slug"];
            background_url: components["schemas"]["AssetPath"];
            /** @enum {string} */
            reward_stage: "weapon" | "companion" | "rescue";
        };
        Spawn: {
            at_tick: number;
            /** @enum {string} */
            enemy_id: "spam-bot" | "clip-cutter" | "caption-blob" | "black-screen-ghost" | "gift-thief" | "censor-frame";
            count: number;
            /** @enum {string} */
            formation: "line" | "fan" | "staggered" | "pincer" | "center" | "sweep";
            interval_ticks: number;
        };
        Wave: {
            id: components["schemas"]["Slug"];
            spawns: components["schemas"]["Spawn"][];
        };
        ContentBossStage: {
            id: components["schemas"]["Slug"];
            health_threshold: number;
            /** @enum {string} */
            move_pattern: "drift" | "sweep" | "dive" | "orbit" | "anchor" | "mirror";
            /** @enum {string} */
            shot_pattern: "aimed" | "fan" | "lane" | "ring" | "delayed" | "beam";
            shot_interval: number;
            projectile_speed: number;
            projectile_damage: number;
            telegraph_ticks: number;
            special: string;
        };
        LocalizedBoss: {
            /** @enum {string} */
            id: "optimal-nana" | "always-on-idol" | "perfect-highlight" | "perfect-captain" | "approved-translation" | "physical-original" | "reality-auditor" | "auto-archive-system";
            name: string;
            description: string;
            sprite_url: components["schemas"]["AssetPath"];
            max_health: number;
            duration_ticks: number;
            stages: components["schemas"]["ContentBossStage"][];
        };
        LocalizedBubble: {
            /** @enum {string} */
            sender_id: "nana7mi" | "jiaran" | "xiangwan" | "bella" | "lulu" | "xingtong" | "nailu" | "system" | "group";
            sender: string;
            text: string;
        };
        LocalizedStoryChoice: {
            id: components["schemas"]["Slug"];
            label: string;
            result: string;
            tag: components["schemas"]["Slug"];
            show_effect_id?: components["schemas"]["Slug"];
        };
        LocalizedIntermission: {
            after_segment: number;
            prompt: string;
            messages: components["schemas"]["LocalizedBubble"][];
            choices: components["schemas"]["LocalizedStoryChoice"][];
        };
        LocalizedStory: {
            prelude: components["schemas"]["LocalizedBubble"][];
            intermission: components["schemas"]["LocalizedIntermission"];
            epilogue: components["schemas"]["LocalizedBubble"][];
            replay_recap: components["schemas"]["LocalizedBubble"][];
        };
        LocalizedEncore: {
            id: components["schemas"]["Slug"];
            name: string;
            description: string;
            enemy_speed_percent: number;
            projectile_speed_percent: number;
            special_charge_penalty_percent: number;
        };
        LocalizedEnding: {
            /** @enum {string} */
            id: "open-archive" | "shared-cut" | "quiet-signoff";
            title: string;
            summary: string;
            messages: components["schemas"]["LocalizedBubble"][];
        };
        LocalizedChapter: {
            id: components["schemas"]["Slug"];
            order: number;
            title: string;
            subtitle: string;
            featured_character: components["schemas"]["Slug"];
            unlock_companion: string;
            background_url: components["schemas"]["AssetPath"];
            segments: components["schemas"]["ContentSegment"][];
            waves: components["schemas"]["Wave"][];
            boss: components["schemas"]["LocalizedBoss"];
            story: components["schemas"]["LocalizedStory"];
            encore: components["schemas"]["LocalizedEncore"][];
            endings: components["schemas"]["LocalizedEnding"][];
        };
        LocalizedDaily: {
            id: components["schemas"]["Slug"];
            title: string;
            subtitle: string;
            /** @constant */
            seed_timezone: "UTC";
            segment_duration_ticks: number;
            /** @constant */
            segment_count: 2;
            /** @constant */
            show_choice_count: 1;
            rotation_characters: components["schemas"]["Slug"][];
            wave_ids: components["schemas"]["Slug"][];
            boss_ids: string[];
            encore_modifier_ids: components["schemas"]["Slug"][];
        };
        GameContent: {
            /** @constant */
            version: "v4";
            /** @constant */
            protocol: "shooter-v1";
            /** @enum {string} */
            locale: "en" | "zh-CN";
            rules: components["schemas"]["Rules"];
            show_effects: components["schemas"]["LocalizedShowEffect"][];
            characters: components["schemas"]["LocalizedCharacter"][];
            companions: components["schemas"]["LocalizedCompanion"][];
            enemies: components["schemas"]["LocalizedEnemy"][];
            chapters: components["schemas"]["LocalizedChapter"][];
            daily: components["schemas"]["LocalizedDaily"];
        };
        Unlock: {
            /** @enum {string} */
            type: "character" | "companion" | "memory_clip";
            content_slug: components["schemas"]["Slug"];
            /** Format: date-time */
            created_at: string;
        };
        StoryChoice: {
            scene_slug: components["schemas"]["Slug"];
            option_slug: components["schemas"]["Slug"];
            choice_tag: components["schemas"]["Slug"];
            revision: number;
            /** Format: date-time */
            created_at: string;
        };
        ChapterProgress: {
            chapter_slug: components["schemas"]["Slug"];
            highest_encore_level: number;
            clears: number;
            best_score: number;
            /** Format: date-time */
            updated_at: string;
        };
        GameProgress: {
            current_chapter_slug: components["schemas"]["Slug"];
            /** @constant */
            story_version: 4;
            /** Format: int64 */
            version: number;
            unlocks: components["schemas"]["Unlock"][];
            choices: components["schemas"]["StoryChoice"][];
            chapters: components["schemas"]["ChapterProgress"][];
            /** @enum {string|null} */
            ending: "open-archive" | "shared-cut" | "quiet-signoff" | null;
            daily_unlocked: boolean;
        };
        RuntimeEffect: {
            /** @enum {string} */
            kind: "twin_shot" | "piercing_shot" | "spread_shot" | "graze_charge" | "guard_on_special" | "pickup_magnet" | "echo_volley" | "boss_break" | "low_health_power" | "combo_extend" | "companion_charge" | "recovery_drop";
            amount: number;
        };
        RuntimeKit: {
            /** @enum {string} */
            id: "nana7mi" | "jiaran" | "xiangwan" | "bella" | "lulu" | "xingtong" | "nailu";
            /** @constant */
            max_health: 3;
            attack_damage: number;
            fire_interval: number;
            rescue_damage: number;
            starting_shield: number;
            move_limit: number;
            /** @enum {string} */
            special_behavior: "barrage_break" | "cheer_guard" | "afterimage_replay" | "captain_parry" | "subtitle_flip" | "prism_shift" | "memory_bloom";
            special_duration: number;
        };
        RuntimeCompanion: {
            /** @enum {string} */
            id: "nana7mi-assist" | "jiaran-assist" | "xiangwan-assist" | "bella-assist" | "lulu-assist" | "xingtong-assist" | "nailu-assist";
            /** @enum {string} */
            trigger: "segment_start" | "graze_streak" | "low_health" | "special_used" | "boss_stage" | "pickup_chain" | "wave_clear";
            /** @enum {string} */
            behavior: "side_shot" | "shield" | "echo_shot" | "clear_lane" | "convert_bullet" | "focus_beam" | "heal";
            amount: number;
            cooldown_ticks: number;
        };
        RuntimeEnemy: {
            /** @enum {string} */
            id: "spam-bot" | "clip-cutter" | "caption-blob" | "black-screen-ghost" | "gift-thief" | "censor-frame";
            /** @enum {string} */
            chassis: "spam-bot" | "clip-cutter" | "caption-blob" | "black-screen-ghost" | "gift-thief" | "censor-frame";
            health: number;
            speed: number;
            contact_damage: number;
            /** @enum {string} */
            move_pattern: "drift" | "sweep" | "dive" | "orbit" | "anchor" | "mirror";
            /** @enum {string} */
            shot_pattern: "aimed" | "fan" | "lane" | "ring" | "delayed" | "beam";
            fire_interval: number;
            projectile_speed: number;
            damage: number;
            score: number;
            telegraph_ticks: number;
            traits: ("shield_link" | "split" | "steal_pickup" | "armor" | "echo" | "jammer")[];
        };
        RuntimeBossStage: {
            id: components["schemas"]["Slug"];
            health_threshold: number;
            move_pattern: string;
            shot_pattern: string;
            fire_interval: number;
            projectile_speed: number;
            damage: number;
            telegraph_ticks: number;
            special?: string;
        };
        RuntimeBoss: {
            /** @enum {string} */
            id: "optimal-nana" | "always-on-idol" | "perfect-highlight" | "perfect-captain" | "approved-translation" | "physical-original" | "reality-auditor" | "auto-archive-system";
            health: number;
            score: number;
            stages: components["schemas"]["RuntimeBossStage"][];
        };
        RuntimeLimits: {
            enemies: number;
            enemy_projectiles: number;
            player_projectiles: number;
            pickups: number;
            effects: number;
        };
        RuntimeConfig: {
            seed: string;
            duration_ticks: number;
            player_health: number;
            starting_rescue_charge: number;
            story_choice_id?: components["schemas"]["Slug"];
            encore_level: number;
            daily: boolean;
            daily_modifier_id?: components["schemas"]["Slug"];
            special_charge_penalty_percent: number;
            kit: components["schemas"]["RuntimeKit"];
            companions: components["schemas"]["RuntimeCompanion"][];
            show_effects: components["schemas"]["RuntimeEffect"][];
            enemies: components["schemas"]["RuntimeEnemy"][];
            wave: components["schemas"]["Wave"];
            boss?: components["schemas"]["RuntimeBoss"];
            limits: components["schemas"]["RuntimeLimits"];
        };
        SegmentState: {
            segment_slug: components["schemas"]["Slug"];
            segment_index: number;
            seed: string;
            duration_ticks: number;
            wave_id?: components["schemas"]["Slug"];
            boss_id?: string;
            /** @enum {string} */
            reward_stage?: "weapon" | "companion" | "rescue";
            background_url: components["schemas"]["AssetPath"];
            runtime_config: components["schemas"]["RuntimeConfig"];
        };
        RunStory: {
            scene_id: components["schemas"]["Slug"];
            choice_ids: components["schemas"]["Slug"][];
        };
        RunState: {
            /** @enum {string} */
            phase: "segment" | "show_choice" | "story" | "completed";
            chapter_slug: components["schemas"]["Slug"];
            character_slug: components["schemas"]["Slug"];
            companion_slugs: components["schemas"]["Slug"][];
            encore_level: number;
            hearts: number;
            /** @constant */
            max_hearts: 3;
            segment_index: number;
            segment?: components["schemas"]["SegmentState"];
            pending_show_options: components["schemas"]["Slug"][];
            show_effects: components["schemas"]["Slug"][];
            story?: components["schemas"]["RunStory"];
            selected_choice_ids: components["schemas"]["Slug"][];
            score: number;
            /** @enum {string} */
            ending_id?: "open-archive" | "shared-cut" | "quiet-signoff";
            daily_variant?: string;
        };
        SegmentOutcome: {
            won: boolean;
            health: number;
            score: number;
        };
        RunEvent: {
            /** @enum {string} */
            kind: "segment_completed" | "show_choice_ready" | "show_effect_chosen" | "companion_chosen" | "intermission_ready" | "intermission_replied" | "ending_choice_ready" | "ending_chosen" | "chapter_cleared";
            segment_slug?: components["schemas"]["Slug"];
            show_effect_id?: components["schemas"]["Slug"];
            scene_id?: components["schemas"]["Slug"];
            choice_id?: components["schemas"]["Slug"];
            choice_tag?: components["schemas"]["Slug"];
            companion_id?: components["schemas"]["Slug"];
            chapter_slug?: components["schemas"]["Slug"];
            next_chapter_slug?: components["schemas"]["Slug"];
            next_character_slug?: components["schemas"]["Slug"];
            /** @enum {string} */
            ending_id?: "open-archive" | "shared-cut" | "quiet-signoff";
        };
        GameRun: {
            /** Format: uuid */
            id: string;
            /** @constant */
            content_version: "v4";
            /** @enum {string} */
            mode: "campaign" | "daily";
            /** Format: date */
            daily_date?: string;
            state: components["schemas"]["RunState"];
            /** @enum {string} */
            status: "active" | "completed" | "abandoned";
            /** @enum {string|null} */
            outcome: "cleared" | "failed" | "abandoned" | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at: string | null;
        };
        DailyResult: {
            /** Format: date */
            date: string;
            character_slug: components["schemas"]["Slug"];
            score: number;
            show_effects: components["schemas"]["Slug"][];
            companion_slugs: components["schemas"]["Slug"][];
            streak: number;
        };
        GameSnapshot: {
            /** @constant */
            protocol: "shooter-v1";
            /** @constant */
            content_version: "v4";
            progress: components["schemas"]["GameProgress"];
            campaign_run: components["schemas"]["GameRun"] | null;
            daily_run: components["schemas"]["GameRun"] | null;
            daily_result: components["schemas"]["DailyResult"] | null;
        };
        CampaignCreateRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "campaign";
            chapter_slug: components["schemas"]["Slug"];
            character_slug: components["schemas"]["Slug"];
            companion_slug?: components["schemas"]["Slug"];
            encore_level?: number;
        };
        DailyCreateRunRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "daily";
        };
        CreateRunRequest: components["schemas"]["CampaignCreateRunRequest"] | components["schemas"]["DailyCreateRunRequest"];
        CompleteSegmentCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "complete_segment";
            /** Format: int64 */
            expected_version: number;
            segment_outcome: components["schemas"]["SegmentOutcome"];
        };
        ChooseShowOptionCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choose_show_option";
            /** Format: int64 */
            expected_version: number;
            option_id: components["schemas"]["Slug"];
        };
        ChooseIntermissionReplyCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choose_intermission_reply";
            /** Format: int64 */
            expected_version: number;
            scene_id: components["schemas"]["Slug"];
            option_id: components["schemas"]["Slug"];
        };
        AbandonRunCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "abandon_run";
            /** Format: int64 */
            expected_version: number;
        };
        RunCommandRequest: components["schemas"]["CompleteSegmentCommand"] | components["schemas"]["ChooseShowOptionCommand"] | components["schemas"]["ChooseIntermissionReplyCommand"] | components["schemas"]["AbandonRunCommand"];
        RunCommandResponse: {
            run: components["schemas"]["GameRun"];
            events: components["schemas"]["RunEvent"][];
        };
        StoryChoiceRequest: {
            scene_slug: components["schemas"]["Slug"];
            option_slug: components["schemas"]["Slug"];
            /** Format: int64 */
            expected_version: number;
        };
        StoryChoiceResponse: {
            progress: components["schemas"]["GameProgress"];
        };
    };
    responses: {
        /** @description Invalid request */
        InvalidRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Content locked */
        Forbidden: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Version or idempotency conflict */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Payload too large */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error */
        InternalError: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unavailable */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ResourceID: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        RequestID: string;
        IdempotencyReplayed: boolean;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getGameContent: {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path: {
                version: "v4";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable localized V4 content */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameContent"];
                };
            };
            /** @description Cached content is current */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getGameState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign and daily state */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Created run */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRun"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative run */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRun"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createRunCommand: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCommandRequest"];
            };
        };
        responses: {
            /** @description Applied command */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    appendStoryChoiceRevision: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryChoiceRequest"];
            };
        };
        responses: {
            /** @description Appended story choice revision */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryChoiceResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPublicDailyResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anonymous daily result referenced by the existing run UUID */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
