/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/content/{version}": {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path: {
                version: "v3";
            };
            cookie?: never;
        };
        get: operations["getGameContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGameState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/runs/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRunCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/story/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createStoryChoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/daily/results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicDailyResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
            version: string;
        };
        Readiness: {
            status: string;
            checks: {
                [key: string]: string;
            };
        };
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                request_id: string;
            };
        };
        Effect: {
            kind: string;
            amount?: number;
            value?: string;
        };
        StoryMetrics: {
            trust: number;
            authenticity: number;
            retention: number;
        };
        EntityLimits: {
            max_enemies: number;
            max_enemy_projectiles: number;
            max_player_projectiles: number;
            max_pickups: number;
            max_effects: number;
        };
        BaseStats: {
            max_health: number;
            attack_damage: number;
            attack_interval: number;
            move_speed: number;
            warp_cooldown: number;
            warp_damage: number;
        };
        CharacterContent: {
            slug: string;
            name: string;
            biography: string;
            playstyle: string;
            color_theme: string;
            portrait_url: string;
            model_url: string;
            kit_slug: string;
        };
        KitContent: {
            slug: string;
            character_slug: string;
            passive: string;
            resonance: string;
            base_stats: components["schemas"]["BaseStats"];
        };
        ModuleBehavior: {
            /** @enum {string} */
            kind: "warp_aftershock" | "graze_guard" | "protocol_echo" | "kill_signal";
            amount: number;
            every?: number;
        };
        ModuleLevelDefinition: {
            effects: components["schemas"]["Effect"][];
            behaviors?: components["schemas"]["ModuleBehavior"][];
        };
        ModuleContent: {
            slug: string;
            character_slug: string | null;
            name: string;
            description: string;
            /** @enum {string} */
            archetype: "surge" | "guard" | "echo" | "glitch";
            /** @enum {string} */
            rarity: "common" | "uncommon" | "rare";
            levels: components["schemas"]["ModuleLevelDefinition"][];
        };
        PluginContent: {
            slug: string;
            character_slug: string | null;
            name: string;
            description: string;
            effects: components["schemas"]["Effect"][];
        };
        Movement: {
            /** @enum {string} */
            kind: "chase" | "orbit" | "strafe" | "charge" | "flee" | "stationary" | "wander";
            amount?: number;
        };
        Attack: {
            /** @enum {string} */
            kind: "aimed" | "fan" | "ring" | "spiral" | "delayed_echo" | "mine" | "beam";
            interval: number;
            projectile_speed: number;
            damage: number;
            count?: number;
            spread?: number;
            telegraph_ticks?: number;
        };
        Trait: {
            /** @enum {string} */
            kind: "linked_shield" | "steal_signal" | "death_split" | "armored" | "distortion_aura" | "teleport";
            amount?: number;
            value?: string;
        };
        EnemyContent: {
            slug: string;
            chapter_slug: string | null;
            name: string;
            description: string;
            /** @enum {string} */
            kind: "normal" | "elite" | "boss";
            max_health: number;
            speed: number;
            contact_damage: number;
            color_theme: string;
            image_url: string;
            movement: components["schemas"]["Movement"];
            attacks: components["schemas"]["Attack"][];
            traits: components["schemas"]["Trait"][];
        };
        Objective: {
            /** @enum {string} */
            kind: "purge" | "stabilize" | "recover" | "holdout" | "elite" | "boss";
            target: number;
        };
        EncounterContent: {
            slug: string;
            chapter_slug: string;
            kind: string;
            objective: components["schemas"]["Objective"];
            duration_ticks: number;
            max_ticks: number;
            spawn_interval: number;
            max_alive: number;
            enemy_slugs: string[];
            hazards: string[];
            reward_bias: string;
            tutorial: boolean;
            risk: number;
        };
        EventOptionContent: {
            slug: string;
            label: string;
            result: string;
            effects: components["schemas"]["Effect"][];
            metrics: components["schemas"]["StoryMetrics"];
        };
        EventContent: {
            slug: string;
            chapter_slug: string;
            title: string;
            body: string;
            options: components["schemas"]["EventOptionContent"][];
        };
        StoryTrigger: {
            kind: string;
            chapter_slug?: string;
            ending?: string;
        };
        StoryMessageContent: {
            sender: string;
            kind: string;
            text: string;
        };
        StoryOptionContent: {
            slug: string;
            label: string;
            metrics: components["schemas"]["StoryMetrics"];
        };
        StorySceneContent: {
            slug: string;
            chapter_slug: string | null;
            title: string;
            trigger: components["schemas"]["StoryTrigger"];
            messages: components["schemas"]["StoryMessageContent"][];
            options: components["schemas"]["StoryOptionContent"][];
        };
        ChapterContent: {
            slug: string;
            order: number;
            title: string;
            subtitle: string;
            character_slug: string | null;
            finale: boolean;
            available: boolean;
            next_chapter_slug: string | null;
            background_url: string;
            kit_slug: string | null;
        };
        GameContent: {
            /** @constant */
            version: "v3";
            /** @constant */
            protocol: "action-v2";
            /** @enum {string} */
            locale: "en" | "zh-CN";
            limits: components["schemas"]["EntityLimits"];
            characters: components["schemas"]["CharacterContent"][];
            kits: components["schemas"]["KitContent"][];
            modules: components["schemas"]["ModuleContent"][];
            plugins: components["schemas"]["PluginContent"][];
            enemies: components["schemas"]["EnemyContent"][];
            encounters: components["schemas"]["EncounterContent"][];
            events: components["schemas"]["EventContent"][];
            scenes: components["schemas"]["StorySceneContent"][];
            chapters: components["schemas"]["ChapterContent"][];
        };
        Unlock: {
            type: string;
            content_slug: string;
            /** Format: date-time */
            created_at: string;
        };
        StoryChoice: {
            scene_slug: string;
            option_slug: string;
            choice_tag: string;
            revision: number;
            trust: number;
            authenticity: number;
            retention: number;
            /** Format: date-time */
            created_at: string;
        };
        ChapterProgress: {
            chapter_slug: string;
            highest_noise_level: number;
            clears: number;
            best_score: number;
            /** Format: date-time */
            updated_at: string;
        };
        GameProgress: {
            current_chapter_slug: string;
            highest_noise_level: number;
            story_version: number;
            /** Format: int64 */
            version: number;
            unlocks: components["schemas"]["Unlock"][];
            choices: components["schemas"]["StoryChoice"][];
            chapters: components["schemas"]["ChapterProgress"][];
            trust: number;
            authenticity: number;
            retention: number;
            ending: string | null;
            daily_unlocked: boolean;
        };
        ModuleLevel: {
            slug: string;
            level: number;
        };
        RuntimeBehavior: {
            source_slug: string;
            level: number;
            /** @enum {string} */
            kind: "warp_aftershock" | "graze_guard" | "protocol_echo" | "kill_signal";
            amount: number;
            every?: number;
        };
        RuntimeConfig: {
            kit: string;
            passive: string;
            resonance: string;
            attack_damage: number;
            attack_interval: number;
            move_speed: number;
            warp_cooldown: number;
            warp_damage: number;
            starting_shield: number;
            overload_bonus: number;
            distortion_gain: number;
            protocol_damage: number;
            protocol_shield: number;
            echo_power: number;
            resonance_power: number;
            projectile_pierce: number;
            projectile_count: number;
            projectile_speed: number;
            graze_radius: number;
            heal_on_protocol: number;
            reflect_damage: number;
            behaviors: components["schemas"]["RuntimeBehavior"][];
        };
        RewardPool: {
            module_slugs: string[];
            plugin_slugs: string[];
        };
        NarrativeModifier: {
            /** @enum {string} */
            reward_bias?: "surge" | "guard" | "echo" | "glitch";
            /** @enum {string} */
            boss_variant: "authentic" | "balanced" | "retained";
            source_scene_slug?: string;
            source_choice_tag?: string;
        };
        MapNode: {
            id: string;
            layer: number;
            lane: number;
            type: string;
            status: string;
            next: string[];
            encounter_slug?: string;
            event_slug?: string;
            objective?: string;
            risk?: number;
            reward_bias?: string;
            enemy_slugs?: string[];
            hazards?: string[];
        };
        RunMap: {
            nodes: components["schemas"]["MapNode"][];
            current_node_id?: string;
        };
        EncounterState: {
            slug: string;
            seed: string;
            kind: string;
            duration_ticks: number;
            max_ticks: number;
            tutorial: boolean;
            objective: components["schemas"]["Objective"];
            risk: number;
            reward_bias: string;
            hazards: string[];
        };
        RewardState: {
            module_choices: string[];
            granted_plugin?: string;
            rerolled: boolean;
        };
        RunState: {
            phase: string;
            chapter_slug: string;
            character_slug: string;
            companion_slugs: string[];
            /** @enum {string} */
            support_alignment?: "authentic" | "balanced" | "retained";
            weapon_slug: string;
            noise_level: number;
            health: number;
            max_health: number;
            modules: components["schemas"]["ModuleLevel"][];
            plugins: string[];
            reward_pool: components["schemas"]["RewardPool"];
            narrative_modifier: components["schemas"]["NarrativeModifier"];
            map: components["schemas"]["RunMap"];
            encounter?: components["schemas"]["EncounterState"];
            reward?: components["schemas"]["RewardState"];
            current_event_slug?: string;
            choice_tags: string[];
            /** Format: int64 */
            rng_cursor: number;
            emergency_reconnect_available: boolean;
            runtime_config: components["schemas"]["RuntimeConfig"];
            rerolls_remaining: number;
            score: number;
        };
        GameRun: {
            /** Format: uuid */
            id: string;
            /** @constant */
            content_version: "v3";
            /** @enum {string} */
            mode: "campaign" | "daily";
            /** Format: date */
            daily_date?: string;
            state: components["schemas"]["RunState"];
            /** @enum {string} */
            status: "active" | "completed" | "abandoned";
            outcome: string | null;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at: string | null;
        };
        GameSnapshot: {
            /** @constant */
            protocol: "action-v2";
            /** @constant */
            content_version: "v3";
            progress: components["schemas"]["GameProgress"];
            campaign_run: components["schemas"]["GameRun"] | null;
            daily_run: components["schemas"]["GameRun"] | null;
            daily_result: components["schemas"]["DailyResult"] | null;
            pending_scene_slug: string | null;
            onboarding_stage: string;
        };
        InputTrace: {
            /** @constant */
            encoding: "rle8-v1";
            ticks: number;
            data: string;
        };
        CreateRunRequest: {
            /** @enum {string} */
            mode: "campaign" | "daily";
            chapter_slug?: string;
            character_slug?: string;
            noise_level?: number;
        };
        RunCommandRequest: {
            /** @enum {string} */
            type: "choose_node" | "complete_encounter" | "choose_module_reward" | "reroll_module_reward" | "resolve_event" | "rest" | "abandon_run";
            /** Format: int64 */
            expected_version: number;
            node_id?: string;
            choice_slug?: string;
            module_slug?: string;
            operation?: string;
            trace?: components["schemas"]["InputTrace"];
        };
        RunEvent: {
            kind: string;
        } & {
            [key: string]: unknown;
        };
        RunCommandResponse: {
            run: components["schemas"]["GameRun"];
            events: components["schemas"]["RunEvent"][];
        };
        StoryChoiceRequest: {
            scene_slug: string;
            option_slug: string;
            /** Format: int64 */
            expected_version: number;
        };
        StoryChoiceResponse: {
            progress: components["schemas"]["GameProgress"];
            pending_scene_slug: string | null;
        };
        DailyResult: {
            /** Format: date */
            date: string;
            character_slug: string;
            score: number;
            modules: components["schemas"]["ModuleLevel"][];
            plugins: string[];
            streak: number;
        };
    };
    responses: {
        /** @description Invalid request */
        InvalidRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Content locked */
        Forbidden: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Version or idempotency conflict */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Payload too large */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal error */
        InternalError: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unavailable */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ResourceID: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        RequestID: string;
        IdempotencyReplayed: boolean;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getGameContent: {
        parameters: {
            query?: {
                locale?: "en" | "zh-CN";
            };
            header?: never;
            path: {
                version: "v3";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable localized V3 content */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameContent"];
                };
            };
            /** @description Cached content is current */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getGameState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign, daily, and story projection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Created run */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRun"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative run */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRun"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createRunCommand: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCommandRequest"];
            };
        };
        responses: {
            /** @description Applied command */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCommandResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createStoryChoice: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryChoiceRequest"];
            };
        };
        responses: {
            /** @description Updated story projection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryChoiceResponse"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublicDailyResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public anonymous daily result cached for five minutes */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
